name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@823c89b659d22b63d7becdc29b8e6c2132fee09e
        with:
          repo-token: ${{ secrets.GRADLE_UPDATE_PAT }}
          pr-title-template: 'chore(deps-dev): Bump Gradle Wrapper from %sourceVersion% to %targetVersion%'
